# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chen Min
email: 781022537@qq.com
description: > # this means to ignore newlines until "baseurl:"
 I'm a devoloper!<br />
 and I play WoW.                 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chenmin1992.github.io" # the base hostname & protocol for your site
github_username:  chenmin1992
qq: 781022537


# Build settings
markdown: kramdown

# paginate
gems: [jekyll-paginate]
paginate: 1000

permalink: none

highlighter: rouge